### ISSUE TITLE
Quantidade de telas

### ISSUE THREAD

**Issue by ARMCardoso** [ARMCardoso/ES2#27]

**Comment by Lflickr** [comment]
Link para a Quantidade de Telas: https://github.com/Milenxsz/ES2/blob/main/Doc/Telas/Quantidade_de_Telas.md

**Comment by GabrielAlves027** [comment]
Atualização Quantidade de Telas: https://github.com/ARMCardoso/ES2/blob/main/Doc/Telas/Quantidade_de_Telas.md
