### ISSUE TITLE
Casos de Uso

### ISSUE THREAD

**Issue by ARMCardoso** [ARMCardoso/ES2#30]

**Comment by Lflickr** [comment]
Link para a listagem dos casos de uso: https://github.com/ARMCardoso/ES2/blob/main/Doc/CasoDeUso/Casos_de_Uso.md

**Comment by GabrielAlves027** [comment]
Atualização Casos de Uso: https://github.com/ARMCardoso/ES2/blob/main/Doc/CasoDeUso/Casos_de_Uso.md
