### ISSUE TITLE
Diagrama de Casos de Uso

### ISSUE THREAD

**Issue by ARMCardoso** [ARMCardoso/ES2#37]

**Comment by Lflickr** [comment]
Utilizando da ferramenta proporcionada pelo site https://online.visual-paradigm.com/pt/ , nós elaboramos o seguinte Diagrama de Casos de Uso: https://github.com/ARMCardoso/ES2/blob/main/Doc/CasoDeUso/Diagrama_CasosDeUso.jpg

**Comment by GabrielAlves027** [comment]
Atualização dos Casos de Uso: Desenho, PlantUML e Lista
https://github.com/ARMCardoso/ES2/tree/main/Doc/CasoDeUso

**Comment by Lflickr** [comment]
Diagrama com o PlantUML: https://github.com/ARMCardoso/ES2/blob/main/README.md

**Comment by GabrielAlves027** [comment]
Atualização dos Casos de Uso para o Sistema de Cabelereiro/Barbeiro e Salão de Beleza.
https://github.com/ARMCardoso/ES2/tree/main/Doc/CasoDeUso
